// <auto-generated />
using System;
using Gestor_de_Rutinas___GYM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestor_de_Rutinas___GYM.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20251027001108_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Altura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Peso")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.DetalleAvanzado", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nota")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PorcentajeRM")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("RM")
                        .HasPrecision(6, 2)
                        .HasColumnType("REAL");

                    b.HasKey("IdDetalle");

                    b.HasIndex("EjercicioId")
                        .IsUnique();

                    b.ToTable("DetallesAvanzados");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.DiaEntrenamiento", b =>
                {
                    b.Property<int>("IdDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RutinaIdRutina")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDia");

                    b.HasIndex("RutinaIdRutina");

                    b.ToTable("DiasEntrenamiento");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Ejercicio", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Descanso")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiaEntrenamientoIdDia")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EjercicioBaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EjercicioBaseIdEjercicioBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEjercicio");

                    b.HasIndex("DiaEntrenamientoIdDia");

                    b.HasIndex("EjercicioBaseId");

                    b.HasIndex("EjercicioBaseIdEjercicioBase");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.EjercicioBase", b =>
                {
                    b.Property<int>("IdEjercicioBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEjercicioBase");

                    b.ToTable("EjerciciosBase");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Rutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionSemana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdRutina");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.DetalleAvanzado", b =>
                {
                    b.HasOne("Gestor_de_Rutinas___GYM.Models.Ejercicio", null)
                        .WithOne("DetalleAvanzado")
                        .HasForeignKey("Gestor_de_Rutinas___GYM.Models.DetalleAvanzado", "EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.DiaEntrenamiento", b =>
                {
                    b.HasOne("Gestor_de_Rutinas___GYM.Models.Rutina", null)
                        .WithMany("Dias")
                        .HasForeignKey("RutinaIdRutina")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Ejercicio", b =>
                {
                    b.HasOne("Gestor_de_Rutinas___GYM.Models.DiaEntrenamiento", null)
                        .WithMany("Ejercicios")
                        .HasForeignKey("DiaEntrenamientoIdDia")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Gestor_de_Rutinas___GYM.Models.EjercicioBase", null)
                        .WithMany()
                        .HasForeignKey("EjercicioBaseId");

                    b.HasOne("Gestor_de_Rutinas___GYM.Models.EjercicioBase", "EjercicioBase")
                        .WithMany()
                        .HasForeignKey("EjercicioBaseIdEjercicioBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioBase");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Rutina", b =>
                {
                    b.HasOne("Gestor_de_Rutinas___GYM.Models.Cliente", null)
                        .WithMany("Rutinas")
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Cliente", b =>
                {
                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.DiaEntrenamiento", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Ejercicio", b =>
                {
                    b.Navigation("DetalleAvanzado");
                });

            modelBuilder.Entity("Gestor_de_Rutinas___GYM.Models.Rutina", b =>
                {
                    b.Navigation("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
